name: Trigger auto deployment for album

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ buildpack ]
    paths:
    - '**'
    - '.github/workflows/album-AutoDeployTrigger-e4821d14-4d50-40e2-a1fc-3c8d63f202ec.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ALBUM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ALBUM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ALBUM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.ALBUM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUM_REGISTRY_PASSWORD }}
          containerAppName: album
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


